### PR TITLE
Add ability to map different types of objects

### PR DESCRIPTION
**Pull request by ealeksandrov**

### CODE REVIEW

**Comment by jamesbrooks** [comment]
From a quick skim, does this allow the use of a protocol rather than subclassing JSONAPIResourceBase? If so a big :+1: :)

**Comment by joshdholtz** [comment]
@jamesbrooks Ahhh, that would be huge
@ealeksandrov Can you confirm? And are there any tests that can be added and updated for this?

**Comment by ealeksandrov** [comment]
Not quite that. This is about supporting different kinds objects for one relationship property.
Added both mapping and serialization support.
Tests also added.

**Comment by tarbrain** [comment]
@joshdholtz Can we please merge this PR?

It adds support for polymorphic types which many API implementations are using.

**Comment by joshdholtz** [comment]
@ealeksandrov @tarbrain Yes yes, thanks for pinging me :blush: Will merge this and push a pod update this morning :+1:

**Comment by joshdholtz** [comment]
@ealeksandrov Thanks for the contribution :raised_hands: Happy holidays!

**Comment by tarbrain** [comment]
Thanks :+1:

**Comment by joshdholtz** [comment]
`1.0.3` should be up on CocoaPods now!

**Pull request merged**
